server:
  port: 9297

spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tdduydev/demo-config-server.git
          clone-on-start: true
