spring:
  main:
    web-application-type: reactive
#    allow-bean-definition-overriding: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          public-key-location: classpath:my-public-key.pub
#    user:
#      name: admin
#      password: 1231234
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**
#          filters:
#            - Name=AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - Name= AuthenticationFilter

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka