spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:my-public-key.pub
    user:
      name: admin
      password: 1231234
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

server:
  port: 8762

