server:
  port: 8762

spring:
  application:
    name: gateway-nosecurity
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
#            ở đây nghĩa là api sau domain bắt đầu bằng /auth-service sẽ được
#            điều hướng đến auth-service còn ở auth-service api được định nghĩa
#            uri như nào vẫn sẽ giữ nguyên ví dụ: /get/ahihi => /auth-service/get/ahihi
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
